# Generated by Django 5.2.10 on 2026-01-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='steps',
            new_name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='transcript',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='youtuber',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
