# Generated by Django 5.2.10 on 2026-01-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recipe_information_recipe_tip_alter_recipe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
