# Generated by Django 5.2.10 on 2026-01-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipe_recipe_title_alter_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_difficulty',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
