# Generated by Django 5.2.10 on 2026-01-28 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recipe_cooking_difficulty_recipe_cooking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('price', models.TextField()),
                ('url', models.URLField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_items', to='main.recipe')),
            ],
        ),
    ]
