# Generated by Django 5.2.10 on 2026-01-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
